### ISSUE TITLE
Некорректный вывод баланса после пополнения меньше максимальной суммы

### ISSUE THREAD

**Issue by DareyBlitz** [Artemova84/Javaqa-team-diplom-2#5]
# Описание
При пополнении сумма баланса остаётся прежней, хотя максимальный лимит не превышается.

# Локация дефекта
https://github.com/Artemova84/Javaqa-team-diplom-2/blob/bfc650ba182f81a0d68b94741f1321ab79544c63/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67-L78

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Artemova84/Javaqa-team-diplom-2/blob/bfc650ba182f81a0d68b94741f1321ab79544c63/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68) в IDEA.
2. Выставить значение переменной `initialBalance` (баланс) в 2000.
3. Выставить значение переменной `minBalance` (минимальный баланс) в 1000.
4. Выставить значение переменной `maxBalance` (максимальный баланс) в 10_000.
5. Выставить значение переменной `rate` (процентная ставка) в 5.
6. Выставить значение переменной `amount` (изменение баланса) в 3000.
7. Запустить тест.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат:* баланс равен 5000.
*Фактический результат:* сумма баланса не изменилась (2000).

# Тестирование бага
https://github.com/Artemova84/Javaqa-team-diplom-2/blob/bfc650ba182f81a0d68b94741f1321ab79544c63/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L14

# Скриншот
![image](https://github.com/Artemova84/Javaqa-team-diplom-2/assets/127688512/c1fcf5d5-da64-419e-acea-3778a5d692eb)

# Окружение
- Операционная система: Windows 10;
- IDE: IntelliJ IDEA Community Edition 2023.1:
- Java: OpenJDK 11

**Comment by Artemova84** [comment]
Ошибка крылась в строке balance = amount, нужен был код balance = balance + amount. Ошибка исправлена.
