### ISSUE TITLE
Не списывается сумма даже при остатке больше минимального баланса

### ISSUE THREAD

**Issue by DareyBlitz** [Artemova84/Javaqa-team-diplom-2#6]
# Описание
Баланс не меняется, даже если списать сумму. При условии, что остаток больше минимального баланса.

# Локация дефекта
https://github.com/Artemova84/Javaqa-team-diplom-2/blob/bfc650ba182f81a0d68b94741f1321ab79544c63/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L43-L54

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Artemova84/Javaqa-team-diplom-2/blob/bfc650ba182f81a0d68b94741f1321ab79544c63/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L43-L54) в IDEA.
2. Выставить значение переменной `initialBalance` (баланс) в 2000.
3. Выставить значение переменной `minBalance` (минимальный баланс) в 1000.
4. Выставить значение переменной `maxBalance` (максимальный баланс) в 10_000.
5. Выставить значение переменной `rate` (процентная ставка) в 5.
6. Выставить значение переменной `amount` (изменение баланса) в 1000.
7. Запустить тест.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат:* баланс равен 1000.
*Фактический результат:* сумма баланса не изменилась (2000).

# Тестирование бага
https://github.com/Artemova84/Javaqa-team-diplom-2/blob/bfc650ba182f81a0d68b94741f1321ab79544c63/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L16-L22

# Скриншот
![image](https://github.com/Artemova84/Javaqa-team-diplom-2/assets/127688512/f2d6739b-160f-46bd-bc43-57f9b802472a)

# Окружение
Операционная система: Windows 10;
IDE: IntelliJ IDEA Community Edition 2023.1:
Java: OpenJDK 11

**Comment by Artemova84** [comment]
Ошибка крылась в строке "balance = balance - amount;", которую нужно было прописать после условия. Кроме того, исправлена ошибка в коде "if (balance - amount >= minBalance)". Здесь нужно было добавить знак равно, чтобы мы могли совершать покупки, если баланс равен минимальному балансу. И вычесть из баланса сумму покупки, чтобы проверить, не превысили ли мы лимит минимального баланса перед тем, как расплачиваться с карты.
