### ISSUE TITLE
Производится расчёт процентов на отрицательный остаток счёта

### ISSUE THREAD

**Issue by DareyBlitz** [Artemova84/Javaqa-team-diplom-2#7]
# Описание
Производится расчёт процентов на отрицательный остаток счёта.

# Локация дефекта
https://github.com/Artemova84/Javaqa-team-diplom-2/blob/bfc650ba182f81a0d68b94741f1321ab79544c63/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Artemova84/Javaqa-team-diplom-2/blob/bfc650ba182f81a0d68b94741f1321ab79544c63/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87-L98) в IDEA.
2. Выставить значение переменной `initialBalance` (баланс) в -2000.
3. Выставить значение переменной `minBalance` (минимальный баланс) в 1000.
4. Выставить значение переменной `maxBalance` (максимальный баланс) в 10_000.
5. Выставить значение переменной `rate` (процентная ставка) в 5.
6. Запустить тест.
7. Посмотреть на вывод в консоли.

*Ожидаемый результат:* проценты на остаток счёта равны 0.
*Фактический результат:* консоль выдаёт ответ -100.

# Тестирование бага
https://github.com/Artemova84/Javaqa-team-diplom-2/blob/3320a625294f772559b0bb843d0e6fa2db8aa06b/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L56-L62

# Скриншот
![image](https://github.com/Artemova84/Javaqa-team-diplom-2/assets/127688512/8f83da1c-7c6e-48e1-81a8-98d981679572)

# Окружение

- Операционная система: Windows 10;
- IDE: IntelliJ IDEA Community Edition 2023.1:
- Java: OpenJDK 11.

**Comment by Artemova84** [comment]
Проценты считались и на отрицательный баланс карты тоже, поэтому в условиях нужно было прописать, что balance > 0.
